### PR TITLE
added the couponGranny code

### PR DESCRIPTION
**Pull request by AminesCodes**
not sure if this pull request will affect others submission (my submission folder has only my code and your old version solution).
Can we please talk about this later on ?

### CODE REVIEW

**Comment by jenesh** [comment]
Have you done a `git pull` before submitting the file? Usually what happens is that if you are trying to make a pull request of a copy that is behind the repository you have to pull and merge the changes. I will definitely show you how to fix this later today in class. So for now I'll leave the pull request open and we'll fix it together in class.

**Comment by AminesCodes** [comment]
That will be much appreciated, thank you

**Comment by AminesCodes** [comment]
The last pull request should be including all updates from your repo (I did a git pull as recommended)

**Comment by jenesh** [comment]
Good job bro you did it correctly. I'll check out your solution as well and compare it with mines. 😁

**Pull request merged**
